from PyQt5 import QtCore, QtGui, QtWidgets

from process import *
from getNewToken import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1022, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1006, 320))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 640))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1005, 299))
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 640))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox.setGeometry(QtCore.QRect(10, 60, 311, 91))
        self.horizontalGroupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalGroupBox.setWhatsThis("")
        self.horizontalGroupBox.setAutoFillBackground(False)
        self.horizontalGroupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.option_two = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_two.sizePolicy().hasHeightForWidth())
        self.option_two.setSizePolicy(sizePolicy)
        self.option_two.setChecked(True)
        self.option_two.setObjectName("option_two")
        self.horizontalLayout.addWidget(self.option_two)
        self.option_one = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_one.sizePolicy().hasHeightForWidth())
        self.option_one.setSizePolicy(sizePolicy)
        self.option_one.setStyleSheet("")
        self.option_one.setChecked(False)
        self.option_one.setObjectName("option_one")
        self.horizontalLayout.addWidget(self.option_one)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 510, 981, 31))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 170, 991, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.horizontalWidget_2.setStyleSheet("QWidget{\n"
"       border: 1px solid black;\n"
"}")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.single_case_count = QtWidgets.QLabel(self.horizontalWidget_2)
        self.single_case_count.setStyleSheet("")
        self.single_case_count.setAlignment(QtCore.Qt.AlignCenter)
        self.single_case_count.setObjectName("singleCaseCount")
        self.horizontalLayout_2.addWidget(self.single_case_count)
        self.split_case_count = QtWidgets.QLabel(self.horizontalWidget_2)
        self.split_case_count.setStyleSheet("")
        self.split_case_count.setAlignment(QtCore.Qt.AlignCenter)
        self.split_case_count.setObjectName("splitCaseCount")
        self.horizontalLayout_2.addWidget(self.split_case_count)
        self.split_manual_case_count = QtWidgets.QLabel(self.horizontalWidget_2)
        self.split_manual_case_count.setStyleSheet("")
        self.split_manual_case_count.setAlignment(QtCore.Qt.AlignCenter)
        self.split_manual_case_count.setObjectName("splitManualCaseCount")
        self.horizontalLayout_2.addWidget(self.split_manual_case_count)
        self.group_case_count = QtWidgets.QLabel(self.horizontalWidget_2)
        self.group_case_count.setStyleSheet("")
        self.group_case_count.setAlignment(QtCore.Qt.AlignCenter)
        self.group_case_count.setObjectName("groupCaseCount")
        self.horizontalLayout_2.addWidget(self.group_case_count)
        self.supplement_case_count = QtWidgets.QLabel(self.horizontalWidget_2)
        self.supplement_case_count.setStyleSheet("")
        self.supplement_case_count.setAlignment(QtCore.Qt.AlignCenter)
        self.supplement_case_count.setObjectName("supplementCaseCount")
        self.horizontalLayout_2.addWidget(self.supplement_case_count)
        self.gridLayout.addWidget(self.horizontalWidget_2, 1, 0, 1, 1)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.layoutWidget)
        self.horizontalWidget_3.setStyleSheet("QWidget{\n"
"       border: 1px solid black;\n"
"}")
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.single_case = QtWidgets.QLabel(self.horizontalWidget_3)
        self.single_case.setEnabled(True)
        self.single_case.setAlignment(QtCore.Qt.AlignCenter)
        self.single_case.setObjectName("single_case")
        self.horizontalLayout_3.addWidget(self.single_case)
        self.split_case = QtWidgets.QLabel(self.horizontalWidget_3)
        self.split_case.setAlignment(QtCore.Qt.AlignCenter)
        self.split_case.setObjectName("split_case")
        self.horizontalLayout_3.addWidget(self.split_case)
        self.split_manual_case = QtWidgets.QLabel(self.horizontalWidget_3)
        self.split_manual_case.setAlignment(QtCore.Qt.AlignCenter)
        self.split_manual_case.setObjectName("split_manual_case")
        self.horizontalLayout_3.addWidget(self.split_manual_case)
        self.group_case = QtWidgets.QLabel(self.horizontalWidget_3)
        self.group_case.setAlignment(QtCore.Qt.AlignCenter)
        self.group_case.setObjectName("group_case")
        self.horizontalLayout_3.addWidget(self.group_case)
        self.supple_case = QtWidgets.QLabel(self.horizontalWidget_3)
        self.supple_case.setAlignment(QtCore.Qt.AlignCenter)
        self.supple_case.setObjectName("supple_case")
        self.horizontalLayout_3.addWidget(self.supple_case)
        self.gridLayout.addWidget(self.horizontalWidget_3, 0, 0, 1, 1)
        self.statusText = QtWidgets.QTextEdit(self.centralwidget)
        self.statusText.setEnabled(True)
        self.statusText.setGeometry(QtCore.QRect(10, 290, 971, 211))
        self.statusText.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statusText.setFont(font)
        self.statusText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.statusText.setObjectName("statusText")
        self.statusText.setReadOnly(True)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox_2.setGeometry(QtCore.QRect(700, 60, 311, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_2.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalGroupBox_2.setWhatsThis("")
        self.horizontalGroupBox_2.setAutoFillBackground(False)
        self.horizontalGroupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FRT = QtWidgets.QCheckBox(self.horizontalGroupBox_2)
        self.FRT.setObjectName("FRT")
        self.horizontalLayout_4.addWidget(self.FRT)
        self.MRI = QtWidgets.QCheckBox(self.horizontalGroupBox_2)
        self.MRI.setObjectName("MRI")
        self.horizontalLayout_4.addWidget(self.MRI)
        self.DMT = QtWidgets.QCheckBox(self.horizontalGroupBox_2)
        self.DMT.setObjectName("DMT")
        self.horizontalLayout_4.addWidget(self.DMT)
        self.TBP = QtWidgets.QCheckBox(self.horizontalGroupBox_2)
        self.TBP.setObjectName("TBP")
        self.horizontalLayout_4.addWidget(self.TBP)
        self.getToken = QtWidgets.QPushButton(self.centralwidget)
        self.getToken.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.getToken.setObjectName("getToken")
        self.envCombobox = QtWidgets.QComboBox(self.centralwidget)
        self.envCombobox.setGeometry(QtCore.QRect(440, 10, 121, 41))
        self.envCombobox.setObjectName("envCombobox")
        self.envCombobox.addItem("")
        self.envCombobox.addItem("")
        self.fromDate = QtWidgets.QLineEdit(self.centralwidget)
        self.fromDate.setGeometry(QtCore.QRect(660, 10, 121, 41))
        self.fromDate.setObjectName("fromDate")
        self.fromDate.setText("20240901")
        self.toDtae = QtWidgets.QLineEdit(self.centralwidget)
        self.toDtae.setGeometry(QtCore.QRect(890, 10, 121, 41))
        self.toDtae.setObjectName("toDtae")
        self.toDtae.setText("20240901")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 20, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 20, 51, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(830, 20, 51, 21))
        self.label_3.setObjectName("label_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(330, 60, 351, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalWidget_4 = QtWidgets.QWidget(self.layoutWidget_2)
        self.horizontalWidget_4.setStyleSheet("QWidget{\n"
"       border: 1px solid black;\n"
"}")
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_14.setStyleSheet("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.gridLayout_2.addWidget(self.horizontalWidget_4, 1, 0, 1, 1)
        self.horizontalWidget_5 = QtWidgets.QWidget(self.layoutWidget_2)
        self.horizontalWidget_5.setStyleSheet("QWidget{\n"
"       border: 1px solid black;\n"
"}")
        self.horizontalWidget_5.setObjectName("horizontalWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.split_manual_case_2 = QtWidgets.QLabel(self.horizontalWidget_5)
        self.split_manual_case_2.setAlignment(QtCore.Qt.AlignCenter)
        self.split_manual_case_2.setObjectName("split_manual_case_2")
        self.horizontalLayout_6.addWidget(self.split_manual_case_2)
        self.group_case_2 = QtWidgets.QLabel(self.horizontalWidget_5)
        self.group_case_2.setAlignment(QtCore.Qt.AlignCenter)
        self.group_case_2.setObjectName("group_case_2")
        self.horizontalLayout_6.addWidget(self.group_case_2)
        self.supple_case_2 = QtWidgets.QLabel(self.horizontalWidget_5)
        self.supple_case_2.setAlignment(QtCore.Qt.AlignCenter)
        self.supple_case_2.setObjectName("supple_case_2")
        self.horizontalLayout_6.addWidget(self.supple_case_2)
        self.gridLayout_2.addWidget(self.horizontalWidget_5, 0, 0, 1, 1)
        self.officeCode = QtWidgets.QComboBox(self.centralwidget)
        self.officeCode.setGeometry(QtCore.QRect(250, 10, 121, 41))
        self.officeCode.setObjectName("officeCode")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.officeCode.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 20, 41, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 21))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_this_tool = QtWidgets.QAction(MainWindow)
        self.actionAbout_this_tool.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAbout_this_tool.setVisible(True)
        self.actionAbout_this_tool.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionAbout_this_tool.setObjectName("actionAbout_this_tool")
        self.menuInfo.addAction(self.actionAbout_this_tool)
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Event
        self.pushButton.clicked.connect(lambda: onFuncButtonClick(self, MainWindow, self.option_one.isChecked()))
                # Nút Read Json vẫn như cũ
        # Kết nối nút Refresh Token với hàm update_config_token (được định nghĩa trong process.py)
        self.getToken.clicked.connect(lambda: updateConfigToken(self, "config.json"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "Option save:"))
        self.option_two.setText(_translate("MainWindow", "Save"))
        self.option_one.setText(_translate("MainWindow", "Save and replace"))
        self.pushButton.setText(_translate("MainWindow", "Read Json"))
        self.single_case_count.setText(_translate("MainWindow", "0"))
        self.split_case_count.setText(_translate("MainWindow", "0"))
        self.split_manual_case_count.setText(_translate("MainWindow", "0"))
        self.group_case_count.setText(_translate("MainWindow", "0"))
        self.supplement_case_count.setText(_translate("MainWindow", "0"))
        self.single_case.setText(_translate("MainWindow", "Single Case"))
        self.split_case.setText(_translate("MainWindow", "Split"))
        self.split_manual_case.setText(_translate("MainWindow", "Split Manual Case"))
        self.group_case.setText(_translate("MainWindow", "Group Case"))
        self.supple_case.setText(_translate("MainWindow", "Supplement"))
        self.statusText.setText(_translate("MainWindow", "Text"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "Source type"))
        self.FRT.setText(_translate("MainWindow", "FRT"))
        self.MRI.setText(_translate("MainWindow", "MRI"))
        self.DMT.setText(_translate("MainWindow", "DMT"))
        self.TBP.setText(_translate("MainWindow", "TBP"))
        self.getToken.setText(_translate("MainWindow", "Get token"))
        self.envCombobox.setItemText(0, _translate("MainWindow", "TEST"))
        self.envCombobox.setItemText(1, _translate("MainWindow", "STG"))
        self.label.setText(_translate("MainWindow", "Env"))
        self.label_2.setText(_translate("MainWindow", "from date:"))
        self.label_3.setText(_translate("MainWindow", "to date:"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "0"))
        self.split_manual_case_2.setText(_translate("MainWindow", "Split Manual Case"))
        self.group_case_2.setText(_translate("MainWindow", "Group Case"))
        self.supple_case_2.setText(_translate("MainWindow", "Supplement"))
        self.officeCode.setItemText(0, _translate("MainWindow", "SINBB"))
        self.officeCode.setItemText(1, _translate("MainWindow", "HKGBB"))
        self.officeCode.setItemText(2, _translate("MainWindow", "SELBB"))
        self.officeCode.setItemText(3, _translate("MainWindow", "PUSBB"))
        self.officeCode.setItemText(4, _translate("MainWindow", "LEHBB"))
        self.officeCode.setItemText(5, _translate("MainWindow", "JKTBB"))
        self.officeCode.setItemText(6, _translate("MainWindow", "OPOBB"))
        self.officeCode.setItemText(7, _translate("MainWindow", "BCNBB"))
        self.officeCode.setItemText(8, _translate("MainWindow", "TPEBB"))
        self.officeCode.setItemText(9, _translate("MainWindow", "SYDBB"))
        self.officeCode.setItemText(10, _translate("MainWindow", "AKLBB"))
        self.label_4.setText(_translate("MainWindow", "office"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionAbout_this_tool.setText(_translate("MainWindow", "About this tool"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
