# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReadMe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadMe(object):
    def setupUi(self, ReadMe):
        ReadMe.setObjectName("ReadMe")
        ReadMe.resize(400, 300)
        self.label = QtWidgets.QLabel(ReadMe)
        self.label.setWordWrap(True)
        self.label.setGeometry(QtCore.QRect(170, 130, 47, 13))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(ReadMe)
        self.pushButton.setGeometry(QtCore.QRect(150, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ReadMe)
        QtCore.QMetaObject.connectSlotsByName(ReadMe)
        self.label.setText("sdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjf;áldjfflsadjfsladjfslakdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjfsdlfaskdjfhsladjflsadjflsadjflsajflsadjlsadkjflasdjfaslkdjfalsdjf")
        self.pushButton.clicked.connect(lambda: ReadMe.close())

    def retranslateUi(self, ReadMe):
        _translate = QtCore.QCoreApplication.translate
        ReadMe.setWindowTitle(_translate("ReadMe", "Dialog"))
        self.label.setText(_translate("ReadMe", "Hello"))
        self.pushButton.setText(_translate("ReadMe", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReadMe = QtWidgets.QDialog()
    ui = Ui_ReadMe()
    ui.setupUi(ReadMe)
    ReadMe.show()

    sys.exit(app.exec_())
